// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebAppElliott.Models;

#nullable disable

namespace MultiPageWebAppElliott.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MultiPageWebAppElliott.Models.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactID = 2,
                            Address = "123 Keats Ave, Tempe, AZ 85209",
                            ContactName = "Tony Robinson",
                            Notes = "D&D DM",
                            PhoneNumber = "5552783000"
                        },
                        new
                        {
                            ContactID = 3,
                            Address = "9876 Boss Dr, Huxley, IA 50023",
                            ContactName = "Derek Ebel",
                            Notes = "Team Leader",
                            PhoneNumber = "5558675309"
                        },
                        new
                        {
                            ContactID = 4,
                            Address = "666 13th St, Boston, MA 10015",
                            ContactName = "Timothy Cross",
                            Notes = "Brother-in-arms",
                            PhoneNumber = "5551234567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
