CREATE TABLE [dbo].[Requests] (
    [requestId]               INT            IDENTITY (1, 1) NOT NULL,
    [materialNumber_id]       NVARCHAR (MAX) NOT NULL,
    [materialDescription_id]  NVARCHAR (MAX) NOT NULL,
    [materialPlant_id]        NVARCHAR (MAX) NOT NULL,
    [materialType_id]         NVARCHAR (MAX) NOT NULL,
    [ProgramType_id]          NVARCHAR (MAX) NOT NULL,
    [productionSloc_id]       NVARCHAR (MAX) NOT NULL,
    [salesOrg_id]             NVARCHAR (MAX) NOT NULL,
    [scenarioType_id]         NVARCHAR (MAX) NOT NULL,
    [old_pn_id]               NVARCHAR (MAX) NOT NULL,
    [sloc_ep_id]              NVARCHAR (MAX) NOT NULL,
    [materialPlantExtend_id]  NVARCHAR (MAX) NOT NULL,
    [productionSlocExtend_id] NVARCHAR (MAX) NOT NULL,
    [salesOrgExtend_id]       NVARCHAR (MAX) NOT NULL,
    [commentBox_id]           NVARCHAR (MAX) NOT NULL,
    [mrp_cntrl_id]            NVARCHAR (MAX) NOT NULL,
    [component_id]            NVARCHAR (MAX) NOT NULL,
    [raw_mat_id]              NVARCHAR (MAX) NOT NULL,
    [authority_id]            NVARCHAR (MAX) NOT NULL,
    [next_higher_assm_id]     NVARCHAR (MAX) NOT NULL,
    [prod_sup_id]             NVARCHAR (MAX) NOT NULL,
    [sto_id]                  NVARCHAR (MAX) NOT NULL,
    [additional_id]           NVARCHAR (MAX) NOT NULL,
    [leadTime_checkbox_id]    NVARCHAR (MAX) NOT NULL,
    [option_EPP_id]           BIT            NOT NULL,
    [option_MRO_id]           BIT            NOT NULL,
    [option_OE_id]            BIT            NOT NULL,
    [primary_sbu_id]          NVARCHAR (MAX) NOT NULL,
    [aog_id]                  NVARCHAR (MAX) NOT NULL,
    [civil_four_radio_id]     NVARCHAR (MAX) NOT NULL,
    [Military_three_radio_id] NVARCHAR (MAX) NOT NULL,
    [civil_one_radio_id]      NVARCHAR (MAX) NOT NULL,
    [buy_id]                  NVARCHAR (MAX) NOT NULL,
    [make_id]                 NVARCHAR (MAX) NOT NULL,
    [extend_id]               NVARCHAR (MAX) NOT NULL,
    [create_id]               NVARCHAR (MAX) NOT NULL,
    [OE_MRO_radio]            NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Requests] PRIMARY KEY CLUSTERED ([requestId] ASC)
);

