// <auto-generated />
using MDPwebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDPwebApp.Migrations
{
    [DbContext(typeof(RequestContext))]
    [Migration("20230628043543_UpdateSqlPath")]
    partial class UpdateSqlPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MDPwebApp.Models.Requestor", b =>
                {
                    b.Property<int>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestId"), 1L, 1);

                    b.Property<bool>("AOG")
                        .HasColumnType("bit");

                    b.Property<bool>("AdditionalCheckBox")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalPlant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalSalesOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalSloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIVL_ITAR_radio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Create_Extend_radio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPSloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LeadTime")
                        .HasColumnType("bit");

                    b.Property<string>("MRPController")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make_Buy_radio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialPlant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextHigherAssembly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OE_MRO_radio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldPartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrimarySBU")
                        .HasColumnType("bit");

                    b.Property<string>("ProdSloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdSupervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("STO")
                        .HasColumnType("bit");

                    b.Property<string>("SalesOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("requestId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            requestId = 1,
                            AOG = false,
                            AdditionalCheckBox = true,
                            AdditionalPlant = "",
                            AdditionalSalesOrg = "",
                            AdditionalSloc = "",
                            Authority = "AUTH",
                            CIVL_ITAR_radio = "",
                            Comment = "Required by Monday",
                            Component = "COM",
                            Create_Extend_radio = "Create",
                            EPSloc = "REC1",
                            LeadTime = false,
                            MRPController = "EAJ",
                            Make_Buy_radio = "Make",
                            MaterialDescription = "SEAL",
                            MaterialNumber = "59568",
                            MaterialPlant = "2020",
                            MaterialType = "Z001",
                            NextHigherAssembly = "NEX",
                            OE_MRO_radio = "",
                            OldPartNumber = "59567",
                            PrimarySBU = true,
                            ProdSloc = "NEW1",
                            ProdSupervisor = "007",
                            ProgramType = "AE250",
                            RawMaterial = "RAW",
                            STO = false,
                            SalesOrg = "4000",
                            Scenario = "END ITEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
